apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashusvc1  # label of svc and don't worry about label of svc its optional 
  name: ashusvc1  #  name  of svc
  namespace: ashu  #  name of ns
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
   run: ashupodd4  # same as pod label 
  type: NodePort
status:
  loadBalancer: {}
