apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashudep111
  name: ashudep111
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashudep111
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashudep111
    spec:
      nodeName: ip-172-31-70-88.ec2.internal  #  manual scheduling  
      volumes:
      - name: ashuvol002  # create a volume
        hostPath:  #  of Host Path type  
         path: /opt/hello  # this directory will be on scheduled worker node persistently 
         type: DirectoryOrCreate  # means if path is not present it will be created
      containers:
      - image: alpine
        name: alpine
        volumeMounts:
        - name: ashuvol002
          mountPath: /mnt/cisco 
        command: ["/bin/sh","-c","while true;do date >>/mnt/cisco/time.txt;sleep 10;done"]
        resources: {}
status: {}
