apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashdbpod
  name: ashudbpod
spec:
  volumes:
  - name: ashudbvol  # name of volume 
    nfs:
     server: 172.31.48.84  #  IP  of NFS 
     path: /data/db/centos #  data path on NFS  server
  containers:
  - image: mysql
    name: dbc1ashu
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: ashudbvol
      mountPath: /var/lib/mysql   #  location side container where nginx logs are generated
    env:
    - name: MYSQL_ROOT_PASSWORD  #  env variable of  MYSQL DB 
      valueFrom:
       secretKeyRef:
        name: ashudbsec  # name of secret
        key: sqlpass     # name of key
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
