apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashwebpod
  name: ashwebpod
spec:
  volumes:
  - name: ashwebvol  # name of volume 
    nfs:
     server: 172.31.48.84  #  IP  of NFS 
     path: /data/web/centos #  data path on NFS  server
  containers:
  - image: nginx
    name: ashwebpod
    ports:
    - containerPort: 80
    volumeMounts:
    - name: ashwebvol
      mountPath: /var/log/nginx   #  location side container where nginx logs are generated
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
