apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashupod3
  name: ashupod3
spec:
  containers:
  - image: alpine
    name: ashupod3
    command: ["/bin/sh","-c","ping  fb.com"]  #  command is a replacement of  entrypoint parent process in Docker image 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
