from  nginx
maintainer  ashutoshh@linux.com 
workdir  /usr/share/nginx/html 
#  user of workdir is to change directory during image build time 
ADD  app1   . 
# similar to copy 
#
# Note:  if  u dont define  CMD or ENTRYPOINT  then  from image parent process will be used 
